# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'TrendingGithubRepos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'Alamofire'
pod 'lottie-ios'

end



target 'TrendingGithubReposUITests' do
  inherit! :search_paths
  pod 'Alamofire'
  pod 'lottie-ios'
end

target 'TrendingGithubReposTests' do
  pod 'Alamofire'
  pod 'lottie-ios'
end
